import { useEffect, useMemo, useState } from "react";
import { Printer, ReceiptText, Search, Trash2, X } from "lucide-react";
import { useJsonCollection } from "../hooks/useJsonCollection";
import { useEmployeeAdjustments } from "../hooks/useEmployeeAdjustments";
import { notify } from "../utils/notify";
import "./ProjectSales.css";
const money = (v, c = "AFN") => `${Number(v || 0).toLocaleString("en-US")} ${c}`;
const itemsOf = (s) => Array.isArray(s.items) && s.items.length ? s.items : [{ projectId: s.projectId, projectName: s.projectName || "Project", price: Number(s.price || 0), quantity: Number(s.quantity || 1), discount: Number(s.discount || 0), subtotal: Number(s.subtotal || s.price || 0), total: Number(s.total || s.price || 0) }];
function ProjectSalesBills() {
  const [sales, setSales] = useJsonCollection("projectSales"); const [transactions, setTransactions] = useJsonCollection("transactions");
  const [employeeAdjustments, setEmployeeAdjustments] = useEmployeeAdjustments(); const [settings] = useJsonCollection("settings");
  const [query, setQuery] = useState(""); const [receiptSale, setReceiptSale] = useState(null); const [deleteTarget, setDeleteTarget] = useState(null); const company = settings[0] || {};
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); const rows = [...sales].sort((a,b) => new Date(b.createdAt || b.saleDate || 0)-new Date(a.createdAt || a.saleDate || 0)); return q ? rows.filter((s) => [s.projectName,s.customerName,s.customerPhone,s.saleDate,...itemsOf(s).map(i=>i.projectName)].some(v=>String(v||"").toLowerCase().includes(q))) : rows; }, [sales, query]);
  useEffect(() => { const id = sessionStorage.getItem("projectSalePrintId"); if (!id || !sales.length) return; const found = sales.find((s) => String(s.id) === String(id)); if (found) { setReceiptSale(found); sessionStorage.removeItem("projectSalePrintId"); setTimeout(() => window.print(), 250); } }, [sales]);
  async function deleteSale() { if (!deleteTarget) return; const id=deleteTarget.id; if (!(await setSales(sales.filter(s=>String(s.id)!==String(id))))) return; await setTransactions(transactions.filter(t=>!(t.source==="project-sale"&&String(t.referenceId||"")===String(id)))); await setEmployeeAdjustments(employeeAdjustments.filter(e=>!(e.source==="project-sale-commission"&&String(e.referenceId||"")===String(id)))); setDeleteTarget(null); notify("Sale deleted successfully.","success"); }
  return <div className="project-sales-page project-bills-page">
    <div className="project-sales-heading"><div><span>Sales / Bills</span><h1>Project Sales Records</h1><p>All completed project sales are stored here. Search, review, print or delete a bill.</p></div></div>
    <div className="project-bills-toolbar"><label><Search size={18}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search bill, customer or project..."/></label><strong>{filtered.length} bills</strong></div>
    <div className="project-bills-table-wrap"><table className="project-bills-table"><thead><tr><th>#</th><th>Date</th><th>Customer</th><th>Projects</th><th>Qty</th><th>Subtotal</th><th>Discount</th><th>Total</th><th>Actions</th></tr></thead><tbody>{filtered.length ? filtered.map((s,index)=>{const items=itemsOf(s); const subtotal=Number(s.subtotal??s.price??0), discount=Number(s.discount||0), total=Number(s.total??s.price??0), qty=Number(s.quantity||items.reduce((a,i)=>a+Number(i.quantity||1),0)); return <tr key={s.id}><td>{index+1}</td><td>{s.saleDate||"-"}</td><td><strong>{s.customerName||"Walk-in Customer"}</strong><small>{s.customerPhone||""}</small></td><td><strong>{items[0]?.projectName||"-"}</strong>{items.length>1&&<small>+{items.length-1} more</small>}</td><td>{qty}</td><td>{money(subtotal,s.currency)}</td><td>{money(discount,s.currency)}</td><td><strong>{money(total,s.currency)}</strong></td><td><div className="project-bill-actions"><button type="button" onClick={()=>setReceiptSale(s)}><Printer size={16}/></button><button type="button" className="danger" onClick={()=>setDeleteTarget(s)}><Trash2 size={16}/></button></div></td></tr>}) : <tr><td colSpan="9"><div className="project-sale-empty">No sales found.</div></td></tr>}</tbody></table></div>
    {receiptSale&&<div className="project-receipt-backdrop" onMouseDown={()=>setReceiptSale(null)}><section className="project-receipt-modal" onMouseDown={e=>e.stopPropagation()}><div className="project-receipt-toolbar no-print"><strong>Sale Bill</strong><div><button type="button" onClick={()=>window.print()}><Printer size={16}/> Print</button><button type="button" onClick={()=>setReceiptSale(null)}><X size={16}/></button></div></div><div className="project-print-receipt"><header><ReceiptText size={28}/><h2>{company.companyName||company.name||"Smart Office"}</h2><p>Project Sales Bill</p></header><div className="project-receipt-meta"><div><span>Bill No</span><strong>{String(receiptSale.id||"").slice(-10).toUpperCase()}</strong></div><div><span>Date</span><strong>{receiptSale.saleDate||"-"}</strong></div><div><span>Customer</span><strong>{receiptSale.customerName||"Walk-in Customer"}</strong></div><div><span>Phone</span><strong>{receiptSale.customerPhone||"-"}</strong></div></div><table><thead><tr><th>Project</th><th>Price</th><th>Qty</th><th>Discount</th><th>Total</th></tr></thead><tbody>{itemsOf(receiptSale).map((i,index)=><tr key={`${i.projectId||i.projectName}-${index}`}><td>{i.projectName}</td><td>{money(i.price,receiptSale.currency)}</td><td>{i.quantity||1}</td><td>{money(i.discount||0,receiptSale.currency)}</td><td>{money(i.total??(Number(i.price||0)*Number(i.quantity||1)-Number(i.discount||0)),receiptSale.currency)}</td></tr>)}</tbody></table><div className="project-receipt-totals"><div><span>Subtotal</span><strong>{money(receiptSale.subtotal??receiptSale.price,receiptSale.currency)}</strong></div><div><span>Discount</span><strong>{money(receiptSale.discount||0,receiptSale.currency)}</strong></div><div className="grand"><span>Grand Total</span><strong>{money(receiptSale.total??receiptSale.price,receiptSale.currency)}</strong></div></div>{receiptSale.notes&&<p className="project-receipt-notes">{receiptSale.notes}</p>}</div></section></div>}
    {deleteTarget&&<div className="project-receipt-backdrop" onMouseDown={()=>setDeleteTarget(null)}><section className="project-delete-dialog" onMouseDown={e=>e.stopPropagation()}><Trash2 size={26}/><h3>Delete Sale?</h3><p>This will remove the bill and its linked income/commission records.</p><div><button type="button" onClick={()=>setDeleteTarget(null)}>Cancel</button><button type="button" className="danger" onClick={deleteSale}>Delete</button></div></section></div>}
  </div>;
}
export default ProjectSalesBills;
