const translations = {
  dr: {
    Dashboard: "داشبورد", Customers: "مشتریان", Projects: "پروژه‌ها", Employees: "کارمندان",
    Suppliers: "تأمین‌کنندگان", Expenses: "مصارف", Finances: "امور مالی",
  "Project License": "جواز پروژه", Reports: "گزارش‌ها", Settings: "تنظیمات",
    "Project Sales": "فروش پروژه‌ها",
    "AI Agent": "دستیار هوشمند", "Recycle Bin": "سطل بازیافت",
    "Consultant Customers": "مشتریان مشاوره", "Travel Customers": "مشتریان سفر",
    "Technology Customers": "مشتریان تکنالوژی", "Media Customers": "مشتریان رسانه",
    "Employee Management": "مدیریت کارمندان", "Add Employee": "افزودن کارمند",
    "Register Employee": "ثبت کارمند", "Full Name": "نام کامل", "Phone Number": "شماره تماس",
    Email: "ایمیل", "NIC Number": "شماره تذکره", Department: "دیپارتمنت", Role: "وظیفه",
    Status: "وضعیت", Notes: "یادداشت", "Contract Start Date": "تاریخ شروع قرارداد",
    "Contract End Date": "تاریخ ختم قرارداد", "Contract File / Image": "فایل یا تصویر قرارداد",
    Cancel: "لغو", "Register Consultant": "ثبت مشتری مشاوره", "Add Consultant": "افزودن مشتری مشاوره",
    "Consultant List": "فهرست مشتریان مشاوره", "Customer Services": "خدمات مشتریان",
    "Full Name in Passport": "نام کامل مطابق پاسپورت", "Education Level": "سطح تحصیل",
    Source: "منبع", "Assign To": "ارجاع به", Purpose: "هدف", Action: "عملیات",
    "Total Consultants": "مجموع مشتریان مشاوره", University: "پوهنتون", Assigned: "ارجاع‌شده",
    "Save Changes": "ذخیره تغییرات", "Delete Consultant?": "مشتری حذف شود؟",
    "Edit Information": "ویرایش معلومات", Analytics: "تحلیل‌ها", "Performance Trends": "روند عملکرد",
    Themes: "پوسته‌ها", Language: "زبان", English: "انگلیسی", Dari: "دری", Pashto: "پشتو",
    "Currency Exchange": "واحد پول", "Display currency": "واحد پول نمایشی",
    "Choose Theme": "انتخاب پوسته", "Interface appearance": "نمای ظاهری برنامه",
    Light: "روشن", Dark: "تیره", Ocean: "اقیانوسی", Warm: "گرم",
    "Light mode": "حالت روشن", "Dark mode": "حالت تیره",
    "Date filter": "فیلتر تاریخ", "All time": "همه زمان‌ها", Today: "امروز",
    "This Week": "این هفته", "This Month": "این ماه", "This Year": "امسال",
    "Custom range": "بازه دلخواه", "Filter dashboard": "فیلتر داشبورد",
    "Select a reporting period": "یک دوره گزارش را انتخاب کنید",
    "From date": "از تاریخ", "To date": "تا تاریخ", "Apply filter": "اعمال فیلتر",
  },
  ps: {
    Dashboard: "ډشبورډ", Customers: "پېرودونکي", Projects: "پروژې", Employees: "کارکوونکي",
    Suppliers: "عرضه کوونکي", Expenses: "لګښتونه", Finances: "مالي چارې",
  "Project License": "د پروژې جواز", Reports: "راپورونه", Settings: "تنظیمات",
    "Project Sales": "د پروژو پلور",
    "AI Agent": "هوښیار مرستیال", "Recycle Bin": "کثافات دانۍ",
    "Consultant Customers": "مشورتي پېرودونکي", "Travel Customers": "سفري پېرودونکي",
    "Technology Customers": "ټکنالوژۍ پېرودونکي", "Media Customers": "رسنیز پېرودونکي",
    "Employee Management": "د کارکوونکو مدیریت", "Add Employee": "کارکوونکی زیات کړئ",
    "Register Employee": "کارکوونکی ثبت کړئ", "Full Name": "بشپړ نوم", "Phone Number": "د تلیفون شمېره",
    Email: "برېښنالیک", "NIC Number": "د تذکرې شمېره", Department: "څانګه", Role: "دنده",
    Status: "حالت", Notes: "یادښت", "Contract Start Date": "د قرارداد پیل",
    "Contract End Date": "د قرارداد پای", "Contract File / Image": "د قرارداد فایل یا انځور",
    Cancel: "لغوه", "Register Consultant": "مشورتي پېرودونکی ثبت کړئ", "Add Consultant": "مشورتي پېرودونکی زیات کړئ",
    "Consultant List": "د مشورتي پېرودونکو لېست", "Customer Services": "د پېرودونکو خدمتونه",
    "Full Name in Passport": "په پاسپورټ کې بشپړ نوم", "Education Level": "د زده کړې کچه",
    Source: "سرچینه", "Assign To": "سپارل", Purpose: "موخه", Action: "عمل",
    "Total Consultants": "ټول مشورتي پېرودونکي", University: "پوهنتون", Assigned: "سپارل شوي",
    "Save Changes": "بدلونونه وساتئ", "Delete Consultant?": "پېرودونکی حذف شي؟",
    "Edit Information": "معلومات سمول", Analytics: "شننه", "Performance Trends": "د فعالیت بهیر",
    Themes: "بڼې", Language: "ژبه", English: "انګلیسي", Dari: "دري", Pashto: "پښتو",
    "Currency Exchange": "د پیسو واحد", "Display currency": "د ښودلو د پیسو واحد",
    "Choose Theme": "بڼه وټاکئ", "Interface appearance": "د پروګرام ظاهري بڼه",
    Light: "روښانه", Dark: "تیاره", Ocean: "سمندري", Warm: "توده",
    "Light mode": "روښانه حالت", "Dark mode": "تیاره حالت",
    "Date filter": "د نېټې فلټر", "All time": "ټول وخت", Today: "نن",
    "This Week": "دا اونۍ", "This Month": "دا میاشت", "This Year": "سږ کال",
    "Custom range": "ځانګړې موده", "Filter dashboard": "ډشبورډ فلټر کړئ",
    "Select a reporting period": "د راپور موده وټاکئ",
    "From date": "له نېټې", "To date": "تر نېټې", "Apply filter": "فلټر پلي کړئ",
  },
};

Object.assign(translations.dr, {
  "Income and Expenses": "عواید و مصارف",
  "Record income and expenses, manage categories, and review the complete financial flow.": "عواید و مصارف را ثبت، دسته‌بندی‌ها را مدیریت و جریان کامل مالی را بررسی کنید.",
  "Add Income or Expense": "افزودن عاید یا مصرف",
  "AFN received": "افغانی دریافت‌شده",
  "AFN spent": "افغانی مصرف‌شده",
  "Net Profit": "سود خالص",
  "Net Loss": "زیان خالص",
  "Difference between income and expenses": "تفاوت میان عواید و مصارف",
  "Financial Overview": "نمای کلی مالی",
  "Compare total income, expenses, and net result.": "مجموع عواید، مصارف و نتیجه خالص را مقایسه کنید.",
  "Income": "عاید",
  "Income, Expenses and Net Result by Date": "عواید، مصارف و نتیجه خالص به تفکیک تاریخ",
  "Review daily financial performance.": "عملکرد مالی روزانه را بررسی کنید.",
  "Transaction Records": "ریکاردهای معاملات",
  "All manual and automatic financial entries.": "تمام ثبت‌های مالی دستی و خودکار.",
  "Search transactions...": "جستجوی معاملات...",
  "All Types": "همه انواع",
  "All Categories": "همه دسته‌ها",
  "No financial records found.": "هیچ ریکارد مالی یافت نشد.",
  "Add Financial Record": "افزودن ریکارد مالی",
  "Edit Financial Record": "ویرایش ریکارد مالی",
  "Income or Expense": "عاید یا مصرف",
  "Expense": "مصرف",
  "Title": "عنوان",
  "Actions": "عملیات",
  "REPORTING CENTER": "مرکز گزارش‌دهی",
  "AVAILABLE REPORT": "گزارش آماده",
  "COMING SOON": "به‌زودی",
  "All customers from every department": "تمام مشتریان از همه بخش‌ها",
  "Sold projects, customers and payments": "پروژه‌های فروخته‌شده، مشتریان و پرداخت‌ها",
  "Employee records and departments": "ریکاردهای کارمندان و بخش‌ها",
  "Suppliers, purchases and balances": "تأمین‌کنندگان، خریدها و بیلانس‌ها",
  "Reception registrations and referrals": "ثبت‌ها و ارجاعات پذیرش",
  "Income, expenses and balances": "عواید، مصارف و بیلانس‌ها",
  "Financial": "مالی",
  "Financial Report": "گزارش مالی",
  "Customer Report": "گزارش مشتریان",
  "Customers Report": "گزارش مشتریان",
  "Projects Report": "گزارش پروژه‌ها",
  "Employees Report": "گزارش کارمندان",
  "Suppliers Report": "گزارش تأمین‌کنندگان",
  "Reception Report": "گزارش پذیرش",
  "OFFICIAL REPORT": "گزارش رسمی",
  "Total Records": "مجموع ریکاردها",
  "Customer Records": "ریکاردهای مشتریان",
  "Project Sales Records": "ریکاردهای فروش پروژه",
  "Employee Records": "ریکاردهای کارمندان",
  "Supplier Records": "ریکاردهای تأمین‌کنندگان",
  "Reception Records": "ریکاردهای پذیرش",
  "No.": "شماره",
  "Record": "ریکارد",
  "Phone": "شماره تماس",
  "Customer": "مشتری",
  "Supplier": "تأمین‌کننده",
  "Date & Time": "تاریخ و زمان",
  "Total Amount": "مبلغ مجموعی",
  "Total Paid": "مجموع پرداخت‌شده",
  "Total Remaining": "مجموع باقی‌مانده",
  "Remaining": "باقی‌مانده",
  "Sold Projects": "پروژه‌های فروخته‌شده",
  "Registered Customers": "مشتریان ثبت‌شده",
  "Total Salary": "مجموع معاش",
  "Net Ledger": "بیلانس خالص",
  "Inactive / Other": "غیرفعال / سایر",
  "Credit": "طلب",
  "Debit": "بدهی",
  "Net Balance": "بیلانس خالص",
  "Total Suppliers": "مجموع تأمین‌کنندگان",
  "Total Purchases": "مجموع خریدها",
  "We Owe Suppliers": "بدهی ما به تأمین‌کنندگان",
  "Suppliers Owe Us": "بدهی تأمین‌کنندگان به ما",
  "Contact Person": "شخص تماس",
  "Supply Type": "نوع تأمین",
  "Purchases": "خریدها",
  "Total Purchase": "مجموع خرید",
  "Last Activity": "آخرین فعالیت",
  "Total Registrations": "مجموع ثبت‌ها",
  "Follow-up / Completed": "پیگیری / تکمیل‌شده",
  "Follow-up": "پیگیری",
  "Country": "کشور",
  "Technology & Media": "تکنالوژی و رسانه",
  "Technology / Media": "تکنالوژی / رسانه",
  "Supplier Expenses": "مصارف تأمین‌کنندگان",
  "Employee Expenses": "مصارف کارمندان",
  "Total Customers": "مجموع مشتریان",
  "All registered customers": "تمام مشتریان ثبت‌شده",
  "Customers in consulting services": "مشتریان بخش خدمات مشاوره",
  "Customers in travel services": "مشتریان بخش خدمات سفر",
  "Customers in technology services": "مشتریان بخش خدمات تکنالوژی",
  "Customers in media services": "مشتریان بخش خدمات رسانه",
  "Total Expenses": "مجموع مصارف",
  "Total recorded business expenses": "مجموع مصارف ثبت‌شدهٔ شرکت",
  "Total Income": "مجموع عواید",
  "Total recorded business income": "مجموع عواید ثبت‌شدهٔ شرکت",
  Profit: "سود",
  "Income minus total expenses": "عواید منهای مجموع مصارف",
  "Overview of the last 6 months": "نمای کلی شش ماه اخیر",
  "Preview trend": "نمایش آزمایشی روند",
  "Last 6 months": "شش ماه اخیر",
  "Human Resources": "منابع بشری",
  "Register employees and manage their contracts and access roles.": "کارمندان، قراردادها و سطح دسترسی آنان را مدیریت کنید.",
  "Total Employees": "مجموع کارمندان",
  "All registered employees": "تمام کارمندان ثبت‌شده",
  "Active Employees": "کارمندان فعال",
  "Currently active team members": "اعضای فعال فعلی تیم",
  "Contracts Ending": "قراردادهای رو به پایان",
  "Ending within 30 days": "پایان‌یابنده در سی روز آینده",
  "Employee List": "فهرست کارمندان",
  "Registered staff and contract information": "معلومات کارمندان و قراردادهای ثبت‌شده",
  Employee: "کارمند",
  Contact: "اطلاعات تماس",
  Contract: "قرارداد",
  to: "تا",
  "No employees have been registered yet.": "هنوز هیچ کارمندی ثبت نشده است.",
  "Complete the employee and contract information.": "معلومات کارمند و قرارداد را تکمیل کنید.",
  "Profile Image": "تصویر پروفایل",
  "Employee preview": "پیش‌نمایش کارمند",
  "Image selected": "تصویر انتخاب شد",
  "Upload profile image": "بارگذاری تصویر پروفایل",
  "Tazkira File / Image": "فایل یا تصویر تذکره",
  "Upload Tazkira document": "بارگذاری سند تذکره",
  "Image or PDF file": "فایل تصویری یا PDF",
  "Upload contract document": "بارگذاری سند قرارداد",
  "Contract image or PDF": "تصویر قرارداد یا فایل PDF",
  "Select departments": "دیپارتمنت‌ها را انتخاب کنید",
  "New department...": "دیپارتمنت جدید...",
  "Select roles": "وظیفه‌ها را انتخاب کنید",
  "New role...": "وظیفهٔ جدید...",
  "Select status": "وضعیت را انتخاب کنید",
  Active: "فعال",
  "On Leave": "در رخصتی",
  Inactive: "غیرفعال",
  "Search employees...": "جستجوی کارمندان...",
  "Register consultant customers and assign them to responsible employees.": "مشتریان مشاوره را ثبت و به کارمندان مسئول ارجاع دهید.",
  "All registered consultants": "تمام مشتریان مشاورهٔ ثبت‌شده",
  "University education": "تحصیلات پوهنتونی",
  "Assigned to employees": "ارجاع‌شده به کارمندان",
  "Registered consultant customer records": "سوابق ثبت‌شدهٔ مشتریان مشاوره",
  "Search consultants...": "جستجوی مشتریان مشاوره...",
  "Full Name": "نام کامل",
  Education: "تحصیلات",
  "Assigned To": "ارجاع‌شده به",
  "Unnamed Consultant": "مشتری بدون نام",
  Unassigned: "ارجاع‌نشده",
  "View details": "نمایش جزئیات",
  Edit: "ویرایش",
  Delete: "حذف",
  "No consultant customers registered yet.": "هنوز هیچ مشتری مشاوره ثبت نشده است.",
  "Edit Consultant Customer": "ویرایش مشتری مشاوره",
  "Register Consultant Customer": "ثبت مشتری مشاوره",
  "Complete the consultant information and employee assignment.": "معلومات مشتری مشاوره و کارمند مربوطه را تکمیل کنید.",
  "Select education": "سطح تحصیل را انتخاب کنید",
  School: "مکتب",
  Institute: "انستیتوت",
  Other: "سایر",
  "School Name": "نام مکتب",
  "University Name": "نام پوهنتون",
  "Enter school name": "نام مکتب را وارد کنید",
  "Enter university name": "نام پوهنتون را وارد کنید",
  "Select employee": "کارمند را انتخاب کنید",
  "Search employee...": "جستجوی کارمند...",
  "Unnamed Employee": "کارمند بدون نام",
  "No employee found.": "کارمندی پیدا نشد.",
  "Consultant Customer": "مشتری مشاوره",
  "School / University": "مکتب یا پوهنتون",
  Registered: "تاریخ ثبت",
  "Delete Consultant": "حذف مشتری مشاوره",
  "You are about to permanently delete": "شما در حال حذف دایمی",
  "this consultant": "این مشتری مشاوره",
  "This action cannot be undone.": "این عمل قابل بازگشت نیست.",
  "Search MAC, Serial, Asset ID, Customer, Tower, Supplier...": "جستجوی مک، سریال، شناسه دارایی، مشتری، برج یا تأمین‌کننده...",
  "Rows per page": "تعداد در هر صفحه",
  Previous: "قبلی",
  Next: "بعدی",
  "Page 1 of 1": "صفحه ۱ از ۱",
  "Showing 1 to 2 of 2 records": "نمایش ۱ تا ۲ از ۲ مورد",
  "Showing 1 to 4 of 4 records": "نمایش ۱ تا ۴ از ۴ مورد",
  Add: "افزودن",
  Save: "ذخیره",
  Update: "به‌روزرسانی",
  Submit: "ثبت",
  Close: "بستن",
  Confirm: "تأیید",
  Yes: "بلی",
  No: "نخیر",
  Name: "نام",
  "First Name": "نام",
  "Last Name": "تخلص",
  Address: "آدرس",
  Date: "تاریخ",
  "Start Date": "تاریخ شروع",
  "End Date": "تاریخ پایان",
  Amount: "مبلغ",
  Description: "توضیحات",
  Details: "جزئیات",
  Type: "نوع",
  Category: "دسته‌بندی",
  Quantity: "تعداد",
  Price: "قیمت",
  Balance: "باقیمانده",
  Search: "جستجو",
  "Select option": "یک گزینه را انتخاب کنید",
  "Choose file": "انتخاب فایل",
  "No file chosen": "فایلی انتخاب نشده",
  Upload: "بارگذاری",
  Download: "دانلود",
  "Created At": "تاریخ ایجاد",
  "Updated At": "تاریخ به‌روزرسانی",
  "Are you sure?": "آیا مطمئن هستید؟",
  "No records found.": "هیچ موردی پیدا نشد.",
  "Please complete at least one field.": "لطفاً حداقل یک فیلد را خانه‌پری کنید.",
  "Edit Employee": "ویرایش کارمند",
  "Delete employee": "حذف کارمند",
  "Delete this employee?": "این کارمند حذف شود؟",
  "Delete Employee": "حذف کارمند",
  "this employee": "این کارمند",
  "Employee updated successfully.": "معلومات کارمند با موفقیت ویرایش شد.",
  "Employee registered successfully.": "کارمند با موفقیت ثبت شد.",
  "Employee record deleted.": "کارمند با موفقیت حذف شد.",
  "No email": "بدون ایمیل",
  "No role": "بدون وظیفه",
  Unspecified: "مشخص‌نشده",
  "Full Admin": "مدیر عمومی",
  Manager: "مدیر",
  "Project Manager": "مدیر پروژه",
  "Finance Manager": "مدیر مالی",
  "HR Officer": "مسئول منابع بشری",
  Supervisor: "سرپرست",
  Accountant: "حسابدار",
  Consultant: "مشاوره",
  Travel: "سفر",
  Technology: "تکنالوژی",
  Media: "رسانه",
  admin: "مدیر",
});

Object.assign(translations.ps, {
  "Total Customers": "ټول پېرودونکي",
  "All registered customers": "ټول ثبت شوي پېرودونکي",
  "Customers in consulting services": "د مشورتي خدمتونو پېرودونکي",
  "Customers in travel services": "د سفر خدمتونو پېرودونکي",
  "Customers in technology services": "د ټکنالوژۍ خدمتونو پېرودونکي",
  "Customers in media services": "د رسنیو خدمتونو پېرودونکي",
  "Total Expenses": "ټول لګښتونه",
  "Total recorded business expenses": "د شرکت ټول ثبت شوي لګښتونه",
  "Total Income": "ټول عاید",
  "Total recorded business income": "د شرکت ټول ثبت شوي عاید",
  Profit: "ګټه",
  "Income minus total expenses": "عاید منفي ټول لګښتونه",
  "Overview of the last 6 months": "د تېرو شپږو میاشتو لنډیز",
  "Preview trend": "د بهیر بېلګه",
  "Last 6 months": "تېرې شپږ میاشتې",
  "Human Resources": "بشري سرچینې",
  "Register employees and manage their contracts and access roles.": "کارکوونکي، قراردادونه او د لاسرسي دندې مدیریت کړئ.",
  "Total Employees": "ټول کارکوونکي",
  "All registered employees": "ټول ثبت شوي کارکوونکي",
  "Active Employees": "فعال کارکوونکي",
  "Currently active team members": "اوسني فعال ټیم غړي",
  "Contracts Ending": "پای ته رسېدونکي قراردادونه",
  "Ending within 30 days": "په راتلونکو دېرشو ورځو کې پای ته رسېږي",
  "Employee List": "د کارکوونکو لېست",
  "Registered staff and contract information": "د ثبت شوو کارکوونکو او قرارداد معلومات",
  Employee: "کارکوونکی",
  Contact: "اړیکه",
  Contract: "قرارداد",
  to: "تر",
  "No employees have been registered yet.": "تر اوسه کوم کارکوونکی نه دی ثبت شوی.",
  "Complete the employee and contract information.": "د کارکوونکي او قرارداد معلومات بشپړ کړئ.",
  "Profile Image": "د پروفایل انځور",
  "Image selected": "انځور وټاکل شو",
  "Upload profile image": "د پروفایل انځور پورته کړئ",
  "Tazkira File / Image": "د تذکرې فایل یا انځور",
  "Upload Tazkira document": "د تذکرې سند پورته کړئ",
  "Image or PDF file": "انځور یا PDF فایل",
  "Upload contract document": "د قرارداد سند پورته کړئ",
  "Contract image or PDF": "د قرارداد انځور یا PDF",
  "Select departments": "څانګې وټاکئ",
  "New department...": "نوې څانګه...",
  "Select roles": "دندې وټاکئ",
  "New role...": "نوې دنده...",
  "Select status": "حالت وټاکئ",
  Active: "فعال",
  "On Leave": "په رخصتۍ",
  Inactive: "غیرفعال",
  "Search employees...": "کارکوونکي ولټوئ...",
  "Register consultant customers and assign them to responsible employees.": "مشورتي پېرودونکي ثبت او مسؤلو کارکوونکو ته یې وسپارئ.",
  "All registered consultants": "ټول ثبت شوي مشورتي پېرودونکي",
  "University education": "پوهنتوني زده کړې",
  "Assigned to employees": "کارکوونکو ته سپارل شوي",
  "Registered consultant customer records": "د مشورتي پېرودونکو ثبت شوي معلومات",
  "Search consultants...": "مشورتي پېرودونکي ولټوئ...",
  "Full Name": "بشپړ نوم",
  Education: "زده کړې",
  "Assigned To": "سپارل شوی",
  "Unnamed Consultant": "بې نومه مشورتي پېرودونکی",
  Unassigned: "نه دی سپارل شوی",
  "View details": "تفصیل وګورئ",
  Edit: "سمول",
  Delete: "حذف",
  "No consultant customers registered yet.": "تر اوسه مشورتي پېرودونکی نه دی ثبت شوی.",
  "Edit Consultant Customer": "مشورتي پېرودونکی سمول",
  "Register Consultant Customer": "مشورتي پېرودونکی ثبتول",
  "Complete the consultant information and employee assignment.": "د مشورتي پېرودونکي او اړوند کارکوونکي معلومات بشپړ کړئ.",
  "Select education": "د زده کړې کچه وټاکئ",
  School: "ښوونځی",
  Institute: "انسټیټیوټ",
  Other: "نور",
  "School Name": "د ښوونځي نوم",
  "University Name": "د پوهنتون نوم",
  "Enter school name": "د ښوونځي نوم ولیکئ",
  "Enter university name": "د پوهنتون نوم ولیکئ",
  "Select employee": "کارکوونکی وټاکئ",
  "Search employee...": "کارکوونکی ولټوئ...",
  "Unnamed Employee": "بې نومه کارکوونکی",
  "No employee found.": "کارکوونکی ونه موندل شو.",
  "Consultant Customer": "مشورتي پېرودونکی",
  "School / University": "ښوونځی یا پوهنتون",
  Registered: "د ثبت نېټه",
  "Delete Consultant": "مشورتي پېرودونکی حذف کړئ",
  "This action cannot be undone.": "دا عمل بېرته نه شي راګرځېدلی.",
  "Search MAC, Serial, Asset ID, Customer, Tower, Supplier...": "MAC، سریال، شتمنۍ، پېرودونکی، برج یا عرضه کوونکی ولټوئ...",
  "Rows per page": "په هره پاڼه کې شمېر",
  Previous: "مخکینی",
  Next: "بل",
  Add: "زیاتول",
  Save: "ساتل",
  Update: "تازه کول",
  Submit: "ثبتول",
  Close: "تړل",
  Confirm: "تایید",
  Yes: "هو",
  No: "نه",
  Name: "نوم",
  Address: "پته",
  Date: "نېټه",
  "Start Date": "د پیل نېټه",
  "End Date": "د پای نېټه",
  Amount: "مبلغ",
  Description: "تشریح",
  Details: "تفصیل",
  Type: "ډول",
  Category: "کټګوري",
  Quantity: "شمېر",
  Price: "بیه",
  Balance: "پاتې پیسې",
  Search: "لټون",
  "Select option": "یو انتخاب وټاکئ",
  "Choose file": "فایل وټاکئ",
  "No file chosen": "فایل نه دی ټاکل شوی",
  Upload: "پورته کول",
  Download: "کښته کول",
  "Are you sure?": "ایا ډاډه یاست؟",
  "No records found.": "هیڅ معلومات ونه موندل شول.",
  "Please complete at least one field.": "لږ تر لږه یو ځای ډک کړئ.",
  "Edit Employee": "کارکوونکی سمول",
  "Delete employee": "کارکوونکی حذفول",
  "Delete this employee?": "دا کارکوونکی حذف شي؟",
  "Delete Employee": "کارکوونکی حذف کړئ",
  "this employee": "دا کارکوونکی",
  "Employee updated successfully.": "د کارکوونکي معلومات په بریالیتوب سم شول.",
  "Employee registered successfully.": "کارکوونکی په بریالیتوب ثبت شو.",
  "Employee record deleted.": "کارکوونکی په بریالیتوب حذف شو.",
  "No email": "برېښنالیک نشته",
  "No role": "دنده نشته",
  Unspecified: "ناټاکلی",
  "Full Admin": "عمومي مدیر",
  Manager: "مدیر",
  "Project Manager": "د پروژې مدیر",
  "Finance Manager": "مالي مدیر",
  "HR Officer": "د بشري سرچینو مسؤل",
  Supervisor: "څارونکی",
  Accountant: "محاسب",
  Consultant: "مشوره",
  Travel: "سفر",
  Technology: "ټکنالوژي",
  Media: "رسنۍ",
  admin: "مدیر",
});

Object.assign(translations.dr, {
  "Project Workspace": "محیط پروژه‌ها",
  "Register customer projects, timelines, budgets, responsibilities, and delivery details.": "پروژه‌های مشتریان، زمان‌بندی، بودجه، مسئولیت‌ها و جزئیات تحویل را ثبت کنید.",
  "Add Project": "افزودن پروژه",
  "Total Projects": "مجموع پروژه‌ها",
  "All customer projects": "تمام پروژه‌های مشتریان",
  "Active Projects": "پروژه‌های فعال",
  "Planning, progress, and review": "برنامه‌ریزی، جریان کار و بررسی",
  "Delivered Projects": "پروژه‌های تحویل‌شده",
  "Completed delivery records": "سوابق تحویل تکمیل‌شده",
  "Priority Projects": "پروژه‌های اولویت‌دار",
  "High and urgent work": "کارهای مهم و عاجل",
  "Search projects...": "جستجوی پروژه‌ها...",
  Planning: "برنامه‌ریزی",
  "In Progress": "در جریان",
  Review: "بررسی",
  Delivered: "تحویل‌شده",
  "On Hold": "متوقف",
  Cancelled: "لغوشده",
  Low: "پایین",
  Medium: "متوسط",
  High: "بلند",
  Urgent: "عاجل",
  "React Application": "برنامه React",
  Website: "وب‌سایت",
  "Desktop Application": "برنامه دسکتاپ",
  "Mobile Application": "برنامه موبایل",
  "ISP System": "سیستم ISP",
  Automation: "اتوماسیون",
  "No description added.": "توضیحی اضافه نشده است.",
  Overdue: "دیرشده",
  Unassigned: "تعیین‌نشده",
  "No projects registered yet.": "هنوز هیچ پروژه‌ای ثبت نشده است.",
  "Add the first customer project from the button above.": "اولین پروژه مشتری را از دکمه بالا اضافه کنید.",
  "Edit Project": "ویرایش پروژه",
  "Register Project": "ثبت پروژه",
  "Complete the standard project information before delivery or licensing.": "پیش از تحویل یا لایسنس، معلومات استاندارد پروژه را تکمیل کنید.",
  "Project Name": "نام پروژه",
  "Already Built Product": "محصول ساخته‌شده قبلی",
  "This product is ready and can be sold to customers.": "این محصول آماده است و می‌تواند به مشتریان فروخته شود.",
  "Build New Project": "ساخت پروژه جدید",
  "This project will be built after customer request.": "این پروژه بعد از درخواست مشتری ساخته می‌شود.",
  "Ordered By": "فرمایش‌دهنده",
  Unit: "واحد",
  Price: "قیمت",
  "Ready Product": "محصول آماده",
  "Product for sale": "محصول برای فروش",
  Available: "موجود",
  "Project name is required.": "نام پروژه ضروری است.",
  Customer: "مشتری",
  "Select customer": "انتخاب مشتری",
  "Customer Name": "نام مشتری",
  "Customer Phone": "شماره مشتری",
  "Register Customer": "ثبت مشتری",
  "Save Customer": "ذخیره مشتری",
  "Add customer": "افزودن مشتری",
  "Customer name is required.": "نام مشتری ضروری است.",
  "Customer registered successfully.": "مشتری موفقانه ثبت شد.",
  "No delivery date": "بدون تاریخ تحویل",
  "Sales Workspace": "محیط فروشات",
  "Project Sales": "فروش پروژه‌ها",
  "Select a project and customer, then record price, payment, remaining balance, and sale type.": "پروژه و مشتری را انتخاب کنید، سپس قیمت، پرداخت، باقی‌مانده و نوع فروش را ثبت کنید.",
  "Total Sales": "مجموع فروشات",
  "Registered project sales": "فروشات ثبت‌شده پروژه‌ها",
  "Sales Value": "ارزش فروشات",
  "Total project price": "مجموع قیمت پروژه‌ها",
  "Total Paid": "مجموع پرداخت",
  "Received payments": "پرداخت‌های دریافت‌شده",
  Remaining: "باقی‌مانده",
  "Outstanding amount": "مبلغ باقی‌مانده",
  "Sale Information": "معلومات فروش",
  "Register Sale": "ثبت فروش",
  "Edit Sale": "ویرایش فروش",
  "Please select project and customer.": "لطفاً پروژه و مشتری را انتخاب کنید.",
  "Project sale updated successfully.": "فروش پروژه موفقانه ویرایش شد.",
  "Project sale registered successfully.": "فروش پروژه موفقانه ثبت شد.",
  "Project sale deleted successfully.": "فروش پروژه موفقانه حذف شد.",
  Paid: "پرداخت",
  "Sale Type": "نوع فروش",
  "Permanent Sale": "فروش دائمی",
  "Sold forever": "برای همیشه فروخته می‌شود",
  "License Sale": "فروش لایسنس",
  "Customer needs a license code": "مشتری به کود لایسنس نیاز دارد",
  "Selected Project": "پروژه انتخاب‌شده",
  "Project details will appear here after selection.": "جزئیات پروژه بعد از انتخاب اینجا نمایش داده می‌شود.",
  "Sales Records": "سوابق فروشات",
  "Project sales and licensing actions.": "فروشات پروژه و عملیات لایسنس.",
  "Search sales...": "جستجوی فروشات...",
  "Give License": "دادن لایسنس",
  "No project sales registered yet.": "هنوز هیچ فروش پروژه‌ای ثبت نشده است.",
  "Source Employee": "کارمند منبع",
  "Assigned To": "ارجاع‌شده به",
  "Service Type": "نوع خدمت",
  Budget: "بودجه",
  Currency: "واحد پول",
  "Due Date": "تاریخ ختم",
  "Delivery Date": "تاریخ تحویل",
  Location: "موقعیت",
  "Repository URL": "آدرس ریپازیتوری",
  "Live URL": "آدرس نشرشده",
  Requirements: "نیازمندی‌ها",
  "Project name and customer are required.": "نام پروژه و مشتری ضروری است.",
  "Project updated successfully.": "پروژه موفقانه ویرایش شد.",
  "Project registered successfully.": "پروژه موفقانه ثبت شد.",
  "Project deleted successfully.": "پروژه موفقانه حذف شد.",
  "Delete Project": "حذف پروژه",
  "Delete this project?": "این پروژه حذف شود؟",
  "License Report": "راپور لایسنس",
  "License Studio": "محیط لایسنس",
  "Review every project license, customer, device, expiry time, and status from one reporting page.": "تمام لایسنس‌های پروژه، مشتری، دستگاه، زمان ختم و حالت را در یک صفحه راپور بررسی کنید.",
  "Licensed Projects": "پروژه‌های لایسنس‌شده",
  "Projects with generated licenses": "پروژه‌هایی که لایسنس دارند",
  "Expiring Soon": "نزدیک به ختم",
  "Ending within seven days": "در هفت روز آینده ختم می‌شود",
  "Select a project first, then create a device license for one day, three days, one week, one month, one year, custom date, or forever.": "اول پروژه را انتخاب کنید، سپس برای Device لایسنس یک‌روزه، سه‌روزه، یک‌هفته، یک‌ماه، یک‌سال، تاریخ دلخواه یا دائمی بسازید.",
  "Active Licenses": "لایسنس‌های فعال",
  "Currently usable licenses": "لایسنس‌های قابل استفاده",
  "Expired Licenses": "لایسنس‌های منقضی",
  "Need renewal or review": "نیازمند تمدید یا بررسی",
  Project: "پروژه",
  "Select Project": "انتخاب پروژه",
  "Choose project": "پروژه را انتخاب کنید",
  "Available for licensing": "آماده برای لایسنس",
  "Project details and license form will appear after selection.": "بعد از انتخاب، جزئیات پروژه و فورم لایسنس نمایش داده می‌شود.",
  "Select a project to continue.": "برای ادامه یک پروژه را انتخاب کنید.",
  "Device License": "لایسنس دستگاه",
  "Generate License": "ساخت لایسنس",
  "Device ID": "شناسه دستگاه",
  "One Day": "یک روز",
  "Three Days": "سه روز",
  "One Week": "یک هفته",
  "One Month": "یک ماه",
  "One Year": "یک سال",
  "Custom Date": "تاریخ دلخواه",
  Forever: "برای همیشه",
  "License Output": "خروجی لایسنس",
  "Generate license to show code": "برای نمایش کود، لایسنس بسازید",
  "Click Generate License to create code": "برای ساخت کود روی ساخت لایسنس کلیک کنید",
  "Generating license code...": "در حال ساخت کود لایسنس...",
  "Generating...": "در حال ساخت...",
  "Secure License Generation requires Electron. Open this screen in the ISP Smart desktop app to generate production licenses.": "تولید امن لایسنس به Electron نیاز دارد. برای ساخت لایسنس واقعی این صفحه را در برنامه دسکتاپ ISP Smart باز کنید.",
  "Paste the Device ID copied from the License page of the installed Customer Electron application.": "Device ID کاپی‌شده از صفحه لایسنس برنامه نصب‌شده Electron مشتری را وارد کنید.",
  "Browser Device IDs cannot be used for production licenses. Copy the Device ID from the customer Electron application.": "Device ID مرورگر برای لایسنس واقعی قابل استفاده نیست. Device ID را از برنامه Electron مشتری کاپی کنید.",
  "License Records": "سوابق لایسنس",
  "Licenses registered for the selected project.": "لایسنس‌های ثبت‌شده برای پروژه انتخاب‌شده.",
  "All generated project licenses.": "تمام لایسنس‌های ساخته‌شده پروژه‌ها.",
  "Search licenses...": "جستجوی لایسنس‌ها...",
  "All Statuses": "تمام حالت‌ها",
  "All Types": "تمام انواع",
  "License Type": "نوع لایسنس",
  "License Key": "کود لایسنس",
  "Remaining Time": "زمان باقی‌مانده",
  "No license has been generated for this project yet.": "هنوز برای این پروژه لایسنس ساخته نشده است.",
  "No license has been generated yet.": "هنوز هیچ لایسنس ساخته نشده است.",
  "Project License Code": "کود لایسنس پروژه",
  "Please select a project first.": "لطفاً اول یک پروژه را انتخاب کنید.",
  "Device ID is required.": "Device ID ضروری است.",
  "License end date is required.": "تاریخ ختم لایسنس ضروری است.",
  "License end date cannot be before the start date.": "تاریخ ختم لایسنس نمی‌تواند قبل از تاریخ شروع باشد.",
  "Custom license end date is required.": "تاریخ ختم برای لایسنس دلخواه ضروری است.",
  "License updated successfully.": "لایسنس موفقانه ویرایش شد.",
  "License generated successfully.": "لایسنس موفقانه ساخته شد.",
  "Secure license saved successfully.": "لایسنس امن موفقانه ذخیره شد.",
  "License deleted successfully.": "لایسنس موفقانه حذف شد.",
  "License key copied.": "کلید لایسنس کاپی شد.",
  Suspended: "تعلیق‌شده",
  Revoked: "باطل‌شده",
  Expired: "منقضی",
  Draft: "پیش‌نویس",
});

Object.assign(translations.ps, {
  "Project Workspace": "د پروژو محیط",
  "Register customer projects, timelines, budgets, responsibilities, and delivery details.": "د پېرودونکو پروژې، وختونه، بودجه، مسؤلیتونه او د سپارلو معلومات ثبت کړئ.",
  "Add Project": "پروژه زیاته کړئ",
  "Total Projects": "ټولې پروژې",
  "All customer projects": "د پېرودونکو ټولې پروژې",
  "Active Projects": "فعالې پروژې",
  "Planning, progress, and review": "پلان، جریان او کتنه",
  "Delivered Projects": "سپارل شوې پروژې",
  "Completed delivery records": "بشپړ شوي د سپارلو ریکارډونه",
  "Priority Projects": "لومړیتوب لرونکې پروژې",
  "High and urgent work": "مهم او عاجل کارونه",
  "Search projects...": "پروژې ولټوئ...",
  Planning: "پلان",
  "In Progress": "په جریان کې",
  Review: "کتنه",
  Delivered: "سپارل شوې",
  "On Hold": "درېدلې",
  Cancelled: "لغوه شوې",
  Low: "ټیټ",
  Medium: "منځنی",
  High: "لوړ",
  Urgent: "عاجل",
  "React Application": "React اپلېکېشن",
  Website: "وېب‌سایټ",
  "Desktop Application": "دسکتاپ اپلېکېشن",
  "Mobile Application": "موبایل اپلېکېشن",
  "ISP System": "ISP سیستم",
  Automation: "اتومات کول",
  "No description added.": "تشریح نه ده اضافه شوې.",
  Overdue: "له وخته تېر",
  Unassigned: "نه دی سپارل شوی",
  "No projects registered yet.": "تر اوسه هېڅ پروژه نه ده ثبت شوې.",
  "Add the first customer project from the button above.": "د پورته تڼۍ څخه لومړۍ پروژه زیاته کړئ.",
  "Edit Project": "پروژه سمه کړئ",
  "Register Project": "پروژه ثبت کړئ",
  "Complete the standard project information before delivery or licensing.": "د سپارلو یا لایسنس مخکې د پروژې معیاري معلومات بشپړ کړئ.",
  "Project Name": "د پروژې نوم",
  "Already Built Product": "له مخکې جوړ محصول",
  "This product is ready and can be sold to customers.": "دا محصول چمتو دی او پېرودونکو ته پلورل کېدای شي.",
  "Build New Project": "نوې پروژه جوړول",
  "This project will be built after customer request.": "دا پروژه د پېرودونکي له غوښتنې وروسته جوړیږي.",
  "Ordered By": "فرمایش ورکوونکی",
  Unit: "واحد",
  Price: "بیه",
  "Ready Product": "چمتو محصول",
  "Product for sale": "د پلور لپاره محصول",
  Available: "موجود",
  "Project name is required.": "د پروژې نوم اړین دی.",
  Customer: "پېرودونکی",
  "Select customer": "پېرودونکی وټاکئ",
  "Customer Name": "د پېرودونکي نوم",
  "Customer Phone": "د پېرودونکي شمېره",
  "Register Customer": "پېرودونکی ثبت کړئ",
  "Save Customer": "پېرودونکی وساتئ",
  "Add customer": "پېرودونکی زیات کړئ",
  "Customer name is required.": "د پېرودونکي نوم اړین دی.",
  "Customer registered successfully.": "پېرودونکی په بریالیتوب ثبت شو.",
  "No delivery date": "د سپارلو نېټه نشته",
  "Sales Workspace": "د پلور محیط",
  "Project Sales": "د پروژو پلور",
  "Select a project and customer, then record price, payment, remaining balance, and sale type.": "پروژه او پېرودونکی وټاکئ، بیا بیه، پرداخت، پاتې پیسې او د پلور ډول ثبت کړئ.",
  "Total Sales": "ټول پلور",
  "Registered project sales": "ثبت شوي د پروژو پلور",
  "Sales Value": "د پلور ارزښت",
  "Total project price": "د پروژو ټول قیمت",
  "Total Paid": "ټول پرداخت",
  "Received payments": "ترلاسه شوي پرداختونه",
  Remaining: "پاتې",
  "Outstanding amount": "پاتې مبلغ",
  "Sale Information": "د پلور معلومات",
  "Register Sale": "پلور ثبت کړئ",
  "Edit Sale": "پلور سم کړئ",
  "Please select project and customer.": "مهرباني وکړئ پروژه او پېرودونکی وټاکئ.",
  "Project sale updated successfully.": "د پروژې پلور په بریالیتوب سم شو.",
  "Project sale registered successfully.": "د پروژې پلور په بریالیتوب ثبت شو.",
  "Project sale deleted successfully.": "د پروژې پلور په بریالیتوب حذف شو.",
  Paid: "پرداخت",
  "Sale Type": "د پلور ډول",
  "Permanent Sale": "دایمي پلور",
  "Sold forever": "تل لپاره پلورل کېږي",
  "License Sale": "د لایسنس پلور",
  "Customer needs a license code": "پېرودونکی د لایسنس کود ته اړتیا لري",
  "Selected Project": "ټاکل شوې پروژه",
  "Project details will appear here after selection.": "د انتخاب وروسته د پروژې جزئیات دلته ښکاري.",
  "Sales Records": "د پلور ریکارډونه",
  "Project sales and licensing actions.": "د پروژې پلور او د لایسنس عملیات.",
  "Search sales...": "پلور ولټوئ...",
  "Give License": "لایسنس ورکول",
  "No project sales registered yet.": "تر اوسه د پروژې پلور نه دی ثبت شوی.",
  "Source Employee": "سرچینه کارکوونکی",
  "Assigned To": "سپارل شوی",
  "Service Type": "د خدمت ډول",
  Budget: "بودجه",
  Currency: "د پیسو واحد",
  "Due Date": "د ختم نېټه",
  "Delivery Date": "د سپارلو نېټه",
  Location: "ځای",
  "Repository URL": "د ریپازیتوري پته",
  "Live URL": "نشر شوې پته",
  Requirements: "اړتیاوې",
  "Project name and customer are required.": "د پروژې نوم او پېرودونکی اړین دي.",
  "Project updated successfully.": "پروژه په بریالیتوب سمه شوه.",
  "Project registered successfully.": "پروژه په بریالیتوب ثبت شوه.",
  "Project deleted successfully.": "پروژه په بریالیتوب حذف شوه.",
  "Delete Project": "پروژه حذف کړئ",
  "Delete this project?": "دا پروژه حذف شي؟",
  "License Report": "د لایسنس راپور",
  "License Studio": "د لایسنس محیط",
  "Review every project license, customer, device, expiry time, and status from one reporting page.": "د هرې پروژې لایسنس، پېرودونکی، دستګاه، د ختم وخت او حالت په یوه راپور پاڼه کې وګورئ.",
  "Licensed Projects": "لایسنس لرونکې پروژې",
  "Projects with generated licenses": "هغه پروژې چې لایسنس لري",
  "Expiring Soon": "ژر ختمېدونکي",
  "Ending within seven days": "په اوو ورځو کې ختمېږي",
  "Select a project first, then create a device license for one day, three days, one week, one month, one year, custom date, or forever.": "لومړی پروژه وټاکئ، بیا د Device لپاره د یوې ورځې، درې ورځو، یوې اونۍ، یوې میاشتې، یوه کال، ځانګړې نېټې یا تل لپاره لایسنس جوړ کړئ.",
  "Active Licenses": "فعال لایسنسونه",
  "Currently usable licenses": "اوس کارېدونکي لایسنسونه",
  "Expired Licenses": "ختم شوي لایسنسونه",
  "Need renewal or review": "تمدید یا کتنې ته اړتیا لري",
  Project: "پروژه",
  "Select Project": "پروژه وټاکئ",
  "Choose project": "پروژه انتخاب کړئ",
  "Available for licensing": "د لایسنس لپاره چمتو",
  "Project details and license form will appear after selection.": "له انتخاب وروسته د پروژې معلومات او د لایسنس فورم ښکاري.",
  "Select a project to continue.": "د دوام لپاره پروژه وټاکئ.",
  "Device License": "د دستګاه لایسنس",
  "Generate License": "لایسنس جوړ کړئ",
  "Device ID": "د دستګاه پېژند",
  "One Day": "یوه ورځ",
  "Three Days": "درې ورځې",
  "One Week": "یوه اونۍ",
  "One Month": "یوه میاشت",
  "One Year": "یو کال",
  "Custom Date": "ځانګړې نېټه",
  Forever: "تل لپاره",
  "License Output": "د لایسنس وتنه",
  "Generate license to show code": "د کود ښودلو لپاره لایسنس جوړ کړئ",
  "Click Generate License to create code": "د کود جوړولو لپاره لایسنس جوړ کړئ کلیک کړئ",
  "Generating license code...": "د لایسنس کود جوړېږي...",
  "Generating...": "جوړېږي...",
  "Secure License Generation requires Electron. Open this screen in the ISP Smart desktop app to generate production licenses.": "د امن لایسنس جوړول Electron ته اړتیا لري. د واقعي لایسنس لپاره دا پاڼه په ISP Smart ډیسکټاپ برنامه کې پرانیزئ.",
  "Paste the Device ID copied from the License page of the installed Customer Electron application.": "د پېرودونکي د نصب شوي Electron اپ د لایسنس پاڼې څخه کاپي شوی Device ID دننه کړئ.",
  "Browser Device IDs cannot be used for production licenses. Copy the Device ID from the customer Electron application.": "د مرورگر Device ID د واقعي لایسنس لپاره نه کارېږي. Device ID د پېرودونکي Electron برنامې څخه کاپي کړئ.",
  "License Records": "د لایسنس ریکارډونه",
  "Licenses registered for the selected project.": "د ټاکل شوې پروژې ثبت شوي لایسنسونه.",
  "All generated project licenses.": "د پروژو ټول جوړ شوي لایسنسونه.",
  "Search licenses...": "لایسنسونه ولټوئ...",
  "All Statuses": "ټول حالتونه",
  "All Types": "ټول ډولونه",
  "License Type": "د لایسنس ډول",
  "License Key": "د لایسنس کود",
  "Remaining Time": "پاتې وخت",
  "No license has been generated for this project yet.": "تر اوسه د دې پروژې لپاره لایسنس نه دی جوړ شوی.",
  "No license has been generated yet.": "تر اوسه هېڅ لایسنس نه دی جوړ شوی.",
  "Project License Code": "د پروژې لایسنس کود",
  "Please select a project first.": "مهرباني وکړئ لومړی پروژه وټاکئ.",
  "Device ID is required.": "Device ID اړین دی.",
  "License end date is required.": "د لایسنس د ختم نېټه اړینه ده.",
  "License end date cannot be before the start date.": "د لایسنس د ختم نېټه د شروع له نېټې مخکې نه شي کېدای.",
  "Custom license end date is required.": "د ځانګړي لایسنس د ختم نېټه اړینه ده.",
  "License updated successfully.": "لایسنس په بریالیتوب سم شو.",
  "License generated successfully.": "لایسنس په بریالیتوب جوړ شو.",
  "Secure license saved successfully.": "امن لایسنس په بریالیتوب خوندي شو.",
  "License deleted successfully.": "لایسنس په بریالیتوب حذف شو.",
  "License key copied.": "د لایسنس کیلي کاپي شوه.",
  Suspended: "ځنډول شوی",
  Revoked: "باطل شوی",
  Expired: "ختم شوی",
  Draft: "مسوده",
});

// Screen-specific vocabulary is kept here so the latest, most complete Dari
// wording wins over older shared labels above.
Object.assign(translations.dr, {
  // Reception and its registration/detail forms
  "Reception": "رسپشن",
  "Reception Registration": "ثبت رسپشن",
  "Customer Registration": "ثبت مشتری",
  "Add Customer": "افزودن مشتری",
  "Customer Information": "معلومات مشتری",
  "Customer Assignment": "تعیین مسئول مشتری",
  "Customer Type": "نوع مشتری",
  "Application Type": "نوع درخواست",
  "Consultation records": "ریکاردهای مشاوره",
  "Travel service records": "ریکاردهای خدمات سفر",
  "Technology service records": "ریکاردهای خدمات تکنالوژی",
  "Media Products": "محصولات رسانه‌ای",
  "Videos and posts": "ویدیوها و پست‌ها",
  "Edit Customer": "ویرایش مشتری",
  "Delete Customer": "حذف مشتری",
  "Delete Customer?": "مشتری حذف شود؟",
  "View customer": "مشاهده مشتری",
  "Close customer details": "بستن جزئیات مشتری",
  "Assign Customer": "تعیین مسئول مشتری",
  "Assign this customer": "این مشتری را تعیین کنید",
  "Change assigned employee": "تغییر کارمند مسئول",
  "Select responsible employee": "کارمند مسئول را انتخاب کنید",
  "Registered through reception": "ثبت‌شده از طریق رسپشن",
  "Registered Date": "تاریخ ثبت",
  "Registered Time": "زمان ثبت",
  "Search customers...": "جستجوی مشتریان...",
  "Search country...": "جستجوی کشور...",
  "Select country": "کشور را انتخاب کنید",
  "Enter full name": "نام کامل را وارد کنید",
  "Enter full name in passport": "نام کامل مطابق پاسپورت را وارد کنید",
  "Enter phone number": "شماره تماس را وارد کنید",
  "Enter email address": "آدرس ایمیل را وارد کنید",
  "Enter customer purpose": "هدف مشتری را وارد کنید",
  "Enter company name": "نام شرکت را وارد کنید",
  "Enter contact number": "شماره تماس را وارد کنید",
  "Enter person name": "نام شخص را وارد کنید",
  "Enter brand name": "نام برند را وارد کنید",
  "Write additional notes": "یادداشت‌های اضافی را بنویسید",
  "Full Name In Passport": "نام کامل مطابق پاسپورت",
  "Company Name": "نام شرکت",
  "Contact Number": "شماره تماس",
  "Person Name": "نام شخص",
  "Brand Name": "نام برند",
  "Educational Level": "سطح تحصیلات",
  "Select source employee": "کارمند منبع را انتخاب کنید",
  "Walk in Customer": "مشتری حضوری",
  "Select employee": "کارمند را انتخاب کنید",
  "Visa Package": "پکیج ویزه",
  "Travel Package": "پکیج سفر",
  "Technology Package": "پکیج تکنالوژی",
  "Media Package": "پکیج رسانه",
  "Select registered visa package": "پکیج ویزه ثبت‌شده را انتخاب کنید",
  "Select registered travel package": "پکیج سفر ثبت‌شده را انتخاب کنید",
  "Select registered technology package": "پکیج تکنالوژی ثبت‌شده را انتخاب کنید",
  "Select registered media package": "پکیج رسانه ثبت‌شده را انتخاب کنید",
  "Loading Visa Packages...": "پکیج‌های ویزه در حال بارگذاری است...",
  "Loading Travel Packages...": "پکیج‌های سفر در حال بارگذاری است...",
  "Loading Technology Packages...": "پکیج‌های تکنالوژی در حال بارگذاری است...",
  "Loading Media Packages...": "پکیج‌های رسانه در حال بارگذاری است...",
  "No available Visa Packages found.": "هیچ پکیج ویزه قابل‌دسترس یافت نشد.",
  "No available Travel Packages found.": "هیچ پکیج سفر قابل‌دسترس یافت نشد.",
  "No Technology Packages have been registered yet.": "هنوز هیچ پکیج تکنالوژی ثبت نشده است.",
  "No Media Packages have been registered yet.": "هنوز هیچ پکیج رسانه ثبت نشده است.",
  "No matching package found.": "پکیج مطابق یافت نشد.",
  "Search package, country or category...": "جستجوی پکیج، کشور یا دسته‌بندی...",
  "SELECTED VISA PACKAGE": "پکیج ویزه انتخاب‌شده",
  "SELECTED TRAVEL PACKAGE": "پکیج سفر انتخاب‌شده",
  "SELECTED TECHNOLOGY PACKAGE": "پکیج تکنالوژی انتخاب‌شده",
  "SELECTED MEDIA PACKAGE": "پکیج رسانه انتخاب‌شده",
  "Bank Statement": "صورت‌حساب بانکی",
  "Documentation": "اسناد مورد نیاز",
  "Package Note": "یادداشت پکیج",
  "Selling Price": "قیمت فروش",
  "Unit": "واحد",
  "Save Media Product": "ذخیره محصول رسانه‌ای",
  "Register Customer": "ثبت مشتری",

  // Finance page, categories, dialogs and manual/contract entries
  "Income and Expense Records": "ریکاردهای عواید و مصارف",
  "Search financial records...": "جستجوی ریکاردهای مالی...",
  "No financial record has been registered yet.": "هنوز هیچ ریکارد مالی ثبت نشده است.",
  "Add Manual Income or Expense": "ثبت دستی عاید یا مصرف",
  "Edit Manual Financial Record": "ویرایش ریکارد مالی دستی",
  "Enter the date, type, title, category, amount, and description.": "تاریخ، نوع، عنوان، دسته‌بندی، مبلغ و توضیحات را وارد کنید.",
  "Enter record title": "عنوان ریکارد را وارد کنید",
  "Enter amount": "مبلغ را وارد کنید",
  "Optional description": "توضیحات اختیاری",
  "New category": "دسته‌بندی جدید",
  "Open actions": "باز کردن عملیات",
  "System record": "ریکارد سیستمی",
  "Delete Financial Record": "حذف ریکارد مالی",
  "Project Sales": "فروش پروژه",
  "Sales Income": "عواید فروش",
  "Services": "خدمات",
  "Assets": "دارایی‌ها",
  "Salary": "معاش",
  "Repair": "ترمیم",
  "Fuel": "تیل",
  "Purchases": "خریدها",
  "Supplier Payment": "پرداخت تأمین‌کننده",
  "Customer Payment": "پرداخت مشتری",
  "Customer Refund": "بازپرداخت به مشتری",
  "Security Deposit": "ودیعه تضمینی",
  "Other": "سایر",
  "Travel Income": "عاید سفر",
  "Travel Expense": "مصرف سفر",
  "Vehicle Expense": "مصرف وسایط",
  "Employee Adjustment": "تعدیل حساب کارمند",
  "System-generated financial records cannot be edited from this page.": "ریکاردهای مالی سیستمی از این صفحه قابل ویرایش نیستند.",
  "Please enter a category name.": "لطفاً نام دسته‌بندی را وارد کنید.",
  "New category added successfully.": "دسته‌بندی جدید با موفقیت افزوده شد.",

  // Settings and all tab forms
  "Settings": "تنظیمات",
  "Choose the system name, logo, and global values used across the app.": "نام سیستم، لوگو و مقادیر عمومی برنامه را تنظیم کنید.",
  "System Identity": "هویت سیستم",
  "App Data": "اطلاعات برنامه",
  "Network Access": "دسترسی شبکه",
  "This logo and name are used in the sidebar, login page, receipts, and reports.": "این لوگو و نام در نوار کناری، صفحه ورود، رسیدها و گزارش‌ها استفاده می‌شود.",
  "System Name": "نام سیستم",
  "System Subtitle": "عنوان فرعی سیستم",
  "Logo": "لوگو",
  "Remove Logo": "حذف لوگو",
  "Save Settings": "ذخیره تنظیمات",
  "Export a backup, import a backup, or clear all saved app data.": "نسخه پشتیبان را صادر یا وارد کنید، یا تمام اطلاعات ذخیره‌شده برنامه را پاک کنید.",
  "Export Data": "صدور اطلاعات",
  "Import Data": "ورود اطلاعات",
  "Automatic Backup": "پشتیبان‌گیری خودکار",
  "Scheduled App Backup": "پشتیبان‌گیری زمان‌بندی‌شده برنامه",
  "Create backup files automatically while ISP Smart is open.": "هنگام باز بودن ISP Smart فایل پشتیبان به‌صورت خودکار ساخته شود.",
  "Enabled": "فعال",
  "Disabled": "غیرفعال",
  "Backup Frequency": "تکرار پشتیبان‌گیری",
  "Backup Time": "زمان پشتیبان‌گیری",
  "Daily": "روزانه",
  "Weekly": "هفته‌وار",
  "Monthly": "ماهانه",
  "Custom": "دلخواه",
  "Day of Week": "روز هفته",
  "Day of Month": "روز ماه",
  "Every Number of Days": "هر چند روز",
  "Sunday": "یک‌شنبه",
  "Monday": "دوشنبه",
  "Tuesday": "سه‌شنبه",
  "Wednesday": "چهارشنبه",
  "Thursday": "پنج‌شنبه",
  "Friday": "جمعه",
  "Saturday": "شنبه",
  "Last Backup": "آخرین پشتیبان",
  "Next Backup": "پشتیبان بعدی",
  "Backup Now": "همین حالا پشتیبان بگیرید",
  "Clear Data": "پاک‌کردن اطلاعات",
  "Type CLEAR, then press Clear Data.": "عبارت CLEAR را تایپ کرده و سپس «پاک‌کردن اطلاعات» را بزنید.",
  "Router / Network": "روتر / شبکه",
  "Save the router name and share the system address with users connected to the same router.": "نام روتر را ذخیره و آدرس سیستم را با کاربران متصل به همان روتر شریک کنید.",
  "Router / Wi-Fi Name": "نام روتر / وای‌فای",
  "Example: Afghan Power Office": "مثال: دفتر افغان پاور",
  "System IP Address": "آدرس IP سیستم",
  "Detected Device": "دستگاه شناسایی‌شده",
  "Backend API": "رابط API بک‌اند",
  "Copy API address": "کاپی آدرس API",
  "Copy system address": "کاپی آدرس سیستم",
  "Share This Address": "این آدرس را شریک کنید",
  "Save Network Settings": "ذخیره تنظیمات شبکه",
  "You are currently connected to this Wi-Fi / network": "شما در حال حاضر به این وای‌فای / شبکه وصل هستید",
  "Share the address below with other users connected to the same Wi-Fi so they can open ISP Smart.": "این آدرس را با کاربران دیگری که به همین وای‌فای وصل هستند شریک بسازید تا بتوانند ISP Smart را باز کنند.",
  "Copy connection address": "کاپی آدرس اتصال",
  "Copy address": "کاپی آدرس",
  "Detected Wi-Fi / Network": "وای‌فای / شبکه شناسایی‌شده",
  "Connected network": "شبکه متصل"
});

const originals = new WeakMap();
let observer;

const englishByTranslation = Object.values(translations).reduce((result, dictionary) => {
  Object.entries(dictionary).forEach(([english, translated]) => {
    result[translated] = english;
  });
  return result;
}, {});

function translatedValue(value, dictionary, language) {
  if (!value) return value;
  // JSX often formats a sentence across several source lines. Normalize only
  // for dictionary matching so those labels translate exactly like one-line text.
  const normalizedValue = value.replace(/\s+/g, " ").trim();
  const canonicalWhole = englishByTranslation[normalizedValue] || normalizedValue;
  if (language === "en") return canonicalWhole;
  if (dictionary[canonicalWhole]) return dictionary[canonicalWhole];
  const englishValue = /[,،]/.test(normalizedValue)
    ? normalizedValue.split(/[,،]/).map((part) => {
        const item = part.trim();
        return englishByTranslation[item] || item;
      }).join(", ")
    : englishByTranslation[normalizedValue] || normalizedValue;
  if (dictionary[englishValue]) return dictionary[englishValue];
  const showing = englishValue.match(/^Showing\s+(\d+)\s+to\s+(\d+)\s+of\s+(\d+)\s+records$/i);
  if (showing) {
    return language === "dr"
      ? `نمایش ${showing[1]} تا ${showing[2]} از ${showing[3]} مورد`
      : `له ${showing[1]} څخه تر ${showing[2]}، د ${showing[3]} ریکارډونو څخه`;
  }
  const page = englishValue.match(/^Page\s+(\d+)\s+of\s+(\d+)$/i);
  if (page) {
    return language === "dr"
      ? `صفحه ${page[1]} از ${page[2]}`
      : `پاڼه ${page[1]} له ${page[2]} څخه`;
  }
  const daysLeft = englishValue.match(/^(\d+)\s+days left$/i);
  if (daysLeft) {
    return language === "dr"
      ? `${daysLeft[1]} روز باقی‌مانده`
      : `${daysLeft[1]} ورځې پاتې`;
  }
  const recordCount = englishValue.match(/^(\d+)\s+record\(s\)$/i);
  if (recordCount) {
    return language === "dr"
      ? `${recordCount[1]} مورد`
      : `${recordCount[1]} ریکارډونه`;
  }
  const numberedDay = englishValue.match(/^Day\s+(\d+)$/i);
  if (numberedDay) {
    return language === "dr" ? `روز ${numberedDay[1]}` : `ورځ ${numberedDay[1]}`;
  }
  if (englishValue.includes(",")) {
    return englishValue
      .split(",")
      .map((part) => {
        const item = part.trim();
        const canonicalItem = englishByTranslation[item] || item;
        return dictionary[canonicalItem] || canonicalItem;
      })
      .join("، ");
  }
  const selected = englishValue.match(/^(\d+)\s+selected$/);
  if (selected) return `${selected[1]} ${dictionary === translations.dr ? "مورد انتخاب شده" : "توکي ټاکل شوي"}`;
  return value;
}

function translateNode(root, language) {
  const dictionary = translations[language] || {};
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let node;
  while ((node = walker.nextNode())) {
    if (!node.parentElement || ["SCRIPT", "STYLE"].includes(node.parentElement.tagName)) continue;
    if (node.parentElement.closest("[data-no-translate]")) continue;
    const savedOriginal = originals.get(node);
    const savedTrimmed = savedOriginal?.trim() || "";
    const currentTrimmed = node.nodeValue.trim();
    const savedTranslation = savedOriginal
      ? translatedValue(savedTrimmed, dictionary, language)
      : null;
    // React can reuse a text node and replace its contents. Do not retain the
    // previous source string when that happens.
    if (!savedOriginal || (currentTrimmed !== savedTrimmed && currentTrimmed !== savedTranslation)) {
      originals.set(node, node.nodeValue);
    }
    const original = originals.get(node);
    const trimmed = original.trim();
    const translated = translatedValue(trimmed, dictionary, language);
    node.nodeValue = trimmed && translated !== trimmed
      ? original.replace(trimmed, translated)
      : original;
  }
  root.querySelectorAll?.("input[placeholder], textarea[placeholder]").forEach((element) => {
    if (!element.dataset.originalPlaceholder) element.dataset.originalPlaceholder = element.placeholder;
    element.placeholder = translatedValue(element.dataset.originalPlaceholder, dictionary, language);
  });
  root.querySelectorAll?.("[title], [aria-label]").forEach((element) => {
    ["title", "aria-label"].forEach((attribute) => {
      if (!element.hasAttribute(attribute)) return;
      const dataKey = `original${attribute === "title" ? "Title" : "AriaLabel"}`;
      if (!element.dataset[dataKey]) element.dataset[dataKey] = element.getAttribute(attribute);
      element.setAttribute(attribute, translatedValue(element.dataset[dataKey], dictionary, language));
    });
  });
}

export function applyInterfaceLanguage(language) {
  localStorage.setItem("isp-language", language);
  document.documentElement.lang = language === "en" ? "en" : language === "dr" ? "fa" : "ps";
  document.documentElement.dir = language === "en" ? "ltr" : "rtl";
  document.body.classList.toggle("lang-rtl", language !== "en");
  translateNode(document.body, language);
  observer?.disconnect();
  observer = new MutationObserver((mutations) => {
    observer.disconnect();
    mutations.forEach((mutation) => {
      if (mutation.type === "characterData") {
        translateNode(mutation.target.parentElement || document.body, language);
        return;
      }
      mutation.addedNodes.forEach((node) => {
        if (node.nodeType === Node.TEXT_NODE) {
          translateNode(node.parentElement || document.body, language);
        } else if (node.nodeType === Node.ELEMENT_NODE) {
          translateNode(node, language);
        }
      });
    });
    observer.observe(document.body, { childList: true, characterData: true, subtree: true });
  });
  observer.observe(document.body, { childList: true, characterData: true, subtree: true });
  window.dispatchEvent(new CustomEvent("isp-language-changed", { detail: language }));
}
